// frontend/pages/cart/index.vue
<template>
  <div class="max-w-7xl mx-auto px-6 py-12">
    <h1 class="text-4xl font-black uppercase tracking-tight mb-10">Bag</h1>
    
    <div v-if="cart.length === 0" class="text-center py-20">
      <p class="text-gray-500 mb-6">There are no items in your bag.</p>
      <NuxtLink to="/" class="bg-brand-black text-brand-white px-8 py-3 rounded-full font-bold uppercase hover:bg-gray-800 transition-colors">
        Shop Now
      </NuxtLink>
    </div>

    <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-12">
      <div class="lg:col-span-2 space-y-8">
        <div v-for="item in cart" :key="item.id" class="flex gap-6 border-b pb-8">
          <div class="w-32 h-32 bg-gray-100 rounded-lg overflow-hidden shrink-0">
             <img 
                src="https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&q=80&w=400" 
                :alt="item.name"
                class="object-cover w-full h-full"
              />
          </div>
          <div class="flex-grow flex flex-col justify-between">
            <div class="flex justify-between">
              <div>
                <h3 class="font-bold text-lg">{{ item.name }}</h3>
                <p class="text-gray-500 text-sm mb-1">Men's Shoes</p>
                <p class="text-gray-500 text-sm mb-4">Size: 42</p>
              </div>
              <p class="font-medium">${{ item.price }}</p>
            </div>
            
            <div class="flex justify-between items-center">
              <div class="flex items-center space-x-4">
                <span class="text-gray-500">Quantity</span>
                <select 
                  :value="item.quantity" 
                  @change="(e) => updateQuantity(item.id, parseInt((e.target as HTMLSelectElement).value))"
                  class="border-gray-300 rounded-md focus:ring-black focus:border-black p-1"
                >
                  <option v-for="n in 10" :key="n" :value="n">{{ n }}</option>
                </select>
              </div>
              <button @click="removeFromCart(item.id)" class="text-gray-400 hover:text-brand-red underline text-sm transition-colors">
                Remove
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="bg-gray-50 p-8 rounded-2xl h-fit">
        <h2 class="text-2xl font-bold mb-6">Summary</h2>
        <div class="space-y-4 mb-6 text-sm">
          <div class="flex justify-between">
            <span class="text-gray-600">Subtotal</span>
            <span>${{ subtotal.toFixed(2) }}</span>
          </div>
          <div class="flex justify-between">
            <span class="text-gray-600">Estimated Delivery & Handling</span>
            <span>Free</span>
          </div>
          <div class="flex justify-between border-t pt-4 font-bold text-lg">
            <span>Total</span>
            <span>${{ subtotal.toFixed(2) }}</span>
          </div>
        </div>
        <button class="w-full bg-brand-black text-brand-white py-4 rounded-full font-bold uppercase hover:bg-gray-800 transition-colors">
          Guest Checkout
        </button>
        <button class="w-full bg-gray-200 text-brand-black py-4 rounded-full font-bold uppercase hover:bg-gray-300 transition-colors mt-3">
          Member Checkout
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const { cart, updateQuantity, removeFromCart } = useCart()

const subtotal = computed(() => {
  return cart.value.reduce((total, item) => total + (item.price * item.quantity), 0)
})
</script>

// frontend/src/app/(store)/cart/page.tsx
"use client";
import { useState } from 'react';
import { useCart } from '@/hooks/useCart';
import { API_URL } from '@/lib/api';

export default function CartPage() {
  const { cartItems, clearCart } = useCart();
  const [isCheckingOut, setIsCheckingOut] = useState(false);

  const handleCheckout = async () => {
    setIsCheckingOut(true);
    try {
      // Simulate network request for production readiness without complex auth
      await new Promise(resolve => setTimeout(resolve, 1000));
      alert('Order placed successfully! Thank you.');
      clearCart();
    } catch (e) {
      alert('Error placing order');
    } finally {
      setIsCheckingOut(false);
    }
  };

  const total = cartItems.reduce((sum, item) => sum + (item.price * item.quantity), 0);

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-black uppercase tracking-tight mb-8">Your Bag</h1>
      
      {cartItems.length > 0 ? (
        <div className="space-y-8">
          <div className="divide-y divide-gray-200">
            {cartItems.map(item => (
              <div key={item.id} className="py-6 flex items-center justify-between">
                <div>
                  <p className="font-bold text-lg">{item.name}</p>
                  <p className="text-gray-500">Quantity: {item.quantity}</p>
                </div>
                <p className="font-medium">${(item.price * item.quantity).toFixed(2)}</p>
              </div>
            ))}
          </div>
          
          <div className="border-t border-gray-200 pt-6 flex justify-between items-center">
            <span className="font-bold text-xl uppercase">Total</span>
            <span className="font-bold text-xl">${total.toFixed(2)}</span>
          </div>
          
          <button disabled={isCheckingOut} onClick={handleCheckout} className="w-full bg-brand-red text-brand-white py-4 rounded-full font-bold uppercase hover:bg-red-600 transition-colors disabled:opacity-50">
            {isCheckingOut ? 'Processing...' : 'Checkout'}
          </button>
        </div>
      ) : (
        <div className="py-20 text-center">
          <p className="text-gray-500 mb-6">There are no items in your bag.</p>
          <a href="/" className="text-brand-black underline font-medium">Continue Shopping</a>
        </div>
      )}
    </div>
  );
}
