// frontend/pages/admin/index.vue
<template>
  <div class="space-y-8">
    <div class="flex justify-between items-center">
      <h1 class="text-3xl font-bold tracking-tight">Overview</h1>
      <div class="flex space-x-2">
        <button class="px-4 py-2 bg-white border border-gray-200 rounded-md text-sm font-medium hover:bg-gray-50 transition-colors">
          Download Report
        </button>
      </div>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div class="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
        <h3 class="text-sm font-medium text-gray-500 mb-1">Total Revenue</h3>
        <p class="text-3xl font-bold tracking-tight">$45,231.89</p>
        <p class="text-sm text-green-600 mt-2 flex items-center">
          <TrendingUpIcon class="w-4 h-4 mr-1" />
          +20.1% from last month
        </p>
      </div>
      <div class="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
        <h3 class="text-sm font-medium text-gray-500 mb-1">Active Orders</h3>
        <p class="text-3xl font-bold tracking-tight">+235</p>
        <p class="text-sm text-green-600 mt-2 flex items-center">
          <TrendingUpIcon class="w-4 h-4 mr-1" />
          +10.5% from last month
        </p>
      </div>
      <div class="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
        <h3 class="text-sm font-medium text-gray-500 mb-1">Total Products</h3>
        <p class="text-3xl font-bold tracking-tight">12</p>
        <p class="text-sm text-gray-500 mt-2">
          +3 added this week
        </p>
      </div>
    </div>

    <!-- Recent Activity Placeholder -->
    <div class="bg-white border border-gray-100 rounded-xl shadow-sm p-6">
      <h2 class="text-lg font-bold mb-4">Recent Activity</h2>
      <div class="space-y-4">
        <div class="flex justify-between items-center py-3 border-b border-gray-50 last:border-0">
          <div class="flex items-center space-x-4">
            <div class="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
              <ShoppingBagIcon class="w-5 h-5 text-gray-500" />
            </div>
            <div>
              <p class="font-medium text-sm">New Order #ORD-492</p>
              <p class="text-xs text-gray-500">2 items &bull; $240.00</p>
            </div>
          </div>
          <span class="text-xs text-gray-400">Just now</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { TrendingUp as TrendingUpIcon, ShoppingBag as ShoppingBagIcon } from 'lucide-vue-next'

definePageMeta({
  layout: 'admin'
})
</script>

// frontend/src/app/admin/page.tsx
export default function AdminDashboard() {
  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-semibold tracking-tight">Overview</h1>
        <button className="bg-brand-black text-brand-white px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-800 transition-colors">
          Download Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="border border-gray-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow bg-white">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Total Revenue</h3>
          <p className="text-3xl font-semibold">$12,450</p>
          <div className="mt-4 flex items-center text-sm text-green-600">
            <span>+14% from last month</span>
          </div>
        </div>
        <div className="border border-gray-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow bg-white">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Active Orders</h3>
          <p className="text-3xl font-semibold">45</p>
          <div className="mt-4 flex items-center text-sm text-brand-red">
            <span>-2% from last month</span>
          </div>
        </div>
        <div className="border border-gray-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow bg-white">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Products in Stock</h3>
          <p className="text-3xl font-semibold">124</p>
        </div>
      </div>

      <div className="border border-gray-200 rounded-xl p-6 bg-white">
        <h2 className="text-lg font-medium mb-4">Recent Activity</h2>
        <div className="space-y-4">
          <div className="flex items-center justify-between py-3 border-b border-gray-100 last:border-0">
            <div>
              <p className="font-medium text-sm">Order #3049</p>
              <p className="text-xs text-gray-500">Placed 2 hours ago</p>
            </div>
            <span className="px-2 py-1 bg-yellow-100 text-yellow-800 text-xs rounded-full">Pending</span>
          </div>
          <div className="flex items-center justify-between py-3 border-b border-gray-100 last:border-0">
            <div>
              <p className="font-medium text-sm">Order #3048</p>
              <p className="text-xs text-gray-500">Placed 5 hours ago</p>
            </div>
            <span className="px-2 py-1 bg-green-100 text-green-800 text-xs rounded-full">Shipped</span>
          </div>
        </div>
      </div>
    </div>
  );
}
